### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by avtkal** [HardcodeCoder/PulseMusic#49] opened 2021-01-29 23:34 UTC
Could it be possible to add a function to edit songs' metadata with Pulse? It would be great to be able to edit songs' names, artists and albums.

**Comment by HardcodeCoder** [comment] 2021-01-30 15:53
Well, you can use any Tag editor to edit your tracks metadata. It will be a nice addition in Pulse Music.  So maybe in future, I shall implement it.

**Comment by HardcodeCoder** [comment] 2021-02-28 09:56
Possible duplicate of #27.

**Closed by HardcodeCoder** 2021-02-28 09:56 UTC
