### ISSUE TITLE
Open with pulse player can't play

### ISSUE THREAD

**Issue by Pranab009** [HardcodeCoder/PulseMusic#47] opened 2021-01-27 04:32 UTC
Thanks for adding "Open audio file via Pulse player."

Now audio files open with "Pulse music player" but it can't play some times when one song is on pause in past.

I thought that any bug present in it.
Please fix it.

**Comment by HardcodeCoder** [comment] 2021-01-27 06:10
Can you share the steps to reproduce? Does it happen everytime when a song is on pause or only with some tracks?

**Comment by Pranab009** [comment] 2021-01-30 10:10
Almost everytime. when a song is on pause.
Last time if the track was paused then this problem happened.

**Comment by HardcodeCoder** [comment] 2021-01-30 10:19
I am not able to reproduce the same as you mentioned. 
Are you able to play the same file, when a song is not paused previously?
Can you please provide additional information:
`Android version:`
`Song file type(s):`
`Settings changed within the app: `
`Steps to reproduce:`

**Comment by Pranab009** [comment] 2021-01-31 04:02
Now i can understand it may be happened due to system battery optimiser.
When i play one file it can't play but if i again play another track (same time) it can play.
But every time when i play from file manager it don't shows its name just show  
" Unknown ".
Is it supported m4a file?
Android version: Android 10  
Song file type(s): opus & m4a.

**Comment by HardcodeCoder** [comment] 2021-02-01 05:14
There are two types of `m4a`. One based on MP3 and the other based on Apple lossless. Android doesn't support Apple lossless. So if you try to play them, it might appear in file managers and in the app, but cannot be played using Android's Navtive codecs (used by Pulse Music).

If the track name or other metadata for the track is unavailable or the app failed to extract,  it will show "unknown". So that's expected.

I assume the issue is not persistent and not directly linked to the app, I am closing this issue as of now. If you find this issue persistent in the app reopen the issue.

**Closed by HardcodeCoder** 2021-02-01 05:14 UTC
